In [1]:
#import library
import pandas as pd

In [30]:
quater1_2020 = pd.read_csv('Jan-March-2020.csv')
quater2_2020 = pd.read_csv('April-Jun-2020.csv')
quater3_2020 = pd.read_csv('Jul-Sept-2020.csv')
quater4_2020 = pd.read_csv('Oct-Dec-2020.csv')
quater1_2021 = pd.read_csv('Jan-March-2021.csv')
quater2_2021 = pd.read_csv('Apr-Jun-2021.csv')

In [4]:
quater1_2020.head(100)

,Datetime,username,tweets,emotions
0,31/3/2020,MuhdIkhwnSfwn,may april bring us hopes and miraclescovd dud...,anger
1,31/3/2020,wmkhair,trlalu bnyk dugaan dn cabaran kita hadapi mo...,anger
2,31/3/2020,saufisufian,day movement control order mco co vi d...,anger
3,31/3/2020,MeRep2p1,rindu nak bebas macam duludulu kitajagak...,love
4,31/3/2020,SaySayLyLy,harga roller sblm ni boleh dpt skrg laku kera...,anger
5,30/3/2020,Deriquecious,surgical myr myig pink shield protect ki...,anger
6,30/3/2020,Zulharith753121,stayathomestaysafekitajagakitacovid,anger
7,30/3/2020,Rajnees54308109,now very difficult because have all countries ...,anger
8,29/3/2020,en_missy7,coronavirusdisease covid kitajagakita stayhom...,anger
9,29/3/2020,Rajnees54308109,rajneesh kumar pal donates rs for the fig...,anger
10,29/3/2020,bekam_senawang,langkah pencegahan bagi wanita hami lcovid sta...,anger
11,28/3/2020,yselangorportal,kita jaga kita ayuh tingkatkan semangat keber...,anger
12,28/3/2020,zizancrew,crowdfunding gpms untuk mahasiswa yang terje...,anger
13,27/3/2020,TEDxKangar,we like this topic it talks about dolphins al...,love
14,27/3/2020,firzhafiz,stay chill th day of lockdown stunning lo...,anger
15,27/3/2020,IrwanBadree,stay safe everyone kitajagakita staysafeevery...,happy
16,27/3/2020,IrwanBadree,stay safe everyone kitajagakita staysafeeveryo...,happy
17,27/3/2020,EdahRusdi,negara wakanda ada kenak covid juak sik,anger
18,27/3/2020,Amenjahhh,its funny how usa claims themselves to be no ...,surprise
19,26/3/2020,KeepMeSafeApp,covid kitajagakitastayathome dudukrumah mala...,anger
20,26/3/2020,zizancrew,buat peminta coffe mari dapat ceo cafe ...,anger
21,26/3/2020,TheCoolxLee,stay at home if you get bored turn on lights...,anger
22,25/3/2020,mesekknyawai,chloroquine and hydrochloroquine are antimala...,anger
23,25/3/2020,mesekknyawai,coronavirus hantavirus influenza virus nile...,anger
24,25/3/2020,TEDxKangar,do nothing at home or learn with te dx kangar...,anger
25,25/3/2020,BuditBliss,cayok malaysia jangan degil ikut arahan mal...,anger
26,24/3/2020,myizad,its not what your country can do for you but w...,anger
27,24/3/2020,mesekknyawai,this is like watching another season of powerr...,sadness
28,24/3/2020,mesekknyawai,lets pray for malaysia and the rest of the wo...,happy
29,24/3/2020,yselangorportal,i stay at work for you you stay at home for us...,anger
...,...,...,...,...
47,20/3/2020,mesekknyawai,y the number of covid cases x the number ...,anger
48,20/3/2020,FaizZakwan_16,tolong duduk di rumah diamdiam lagu cowok ba...,anger
49,20/3/2020,ladiefarah,staysafe stayathome kak fa keluar tak sampai...,anger
50,19/3/2020,fancyjackry1992,selamat pagi selamat menjemput rezeki awal b...,happy
51,19/3/2020,fancyjackry1992,macam mana pula dengan situasi adik aku yang s...,anger
52,19/3/2020,BuditBliss,if u think this weeks self quarantine is too l...,anger
53,19/3/2020,AhmedElneil96,quarantine huh stay home explore your imagina...,anger
54,19/3/2020,bekam_senawang,sila duduk jangan lari covidstayathomearay...,anger
55,18/3/2020,Rajnees54308109,hello sir mujhe help chahiye mai iss time mala...,anger
56,18/3/2020,ILLYASAZMEER,hey domestic flight can change due to corona v...,anger
57,18/3/2020,bbhayati_,sharing about covid everydayyy,anger
58,18/3/2020,MNZAchaon95,hargai jasa mereka yang berjuang covid cor...,anger
59,18/3/2020,Rajnees54308109,hi madam mujhe help chahiye mai iss time malay...,anger
60,18/3/2020,shedahv_v,mula aku risau kes corona je ha skrg ni rumah...,surprise
61,18/3/2020,Amenjahhh,wow almost everyone in the world have one thin...,sadness
62,17/3/2020,Cikk_Azie,be safe everyone stay at home quarantine your...,happy
63,17/3/2020,FaizZakwan_16,firman allah swt wahai orangorang yang beri...,anger
64,17/3/2020,Acapvilla_,please take care of yourself covid malaysia,anger
65,17/3/2020,AnakGhazi,this too shall pass in the grand scale of thi...,happy
66,17/3/2020,ezzanyashraaf,be safe mask on covid malaysia,happy
67,17/3/2020,ayie0109,malaysias movement control order march th...,anger
68,16/3/2020,BuditBliss,dengar cerita wwe wrestlemania tahun ni akan ...,happy
69,14/3/2020,fadzoners,cara cegah covid ini salah satu cara ye per...,anger
70,13/3/2020,bbhayati_,ijtimak tabligh in malaysia dah mcm mass gathe...,sadness
71,13/3/2020,hilmijaidie,my grandma called me and her first question wa...,anger
72,12/3/2020,sahida_sahira,selamat pageyyy lovelies sedikit tips drpd ...,anger
73,16/2/2020,___Syahrul,corona kau jangan buat hal la,love
74,26/1/2020,azrnyenn,everybody thought tht is gonna be their year ...,happy
75,26/1/2020,mesekknyawai,as a biology teacher and an ex biology studen...,anger
76,26/1/2020,feirudin,malaysian its coronavirus we need to protec...,anger

In [6]:
emotion_count = quater1_2020.groupby('emotions').count()
emotion_sum = sum(emotion_count.tweets)
emotion_count.tweets = (emotion_count.tweets * 100 / emotion_sum).round(2)
emotion_count.tweets

emotions
anger       72.73
fear         2.60
happy       12.99
love         3.90
sadness      5.19
surprise     2.60
Name: tweets, dtype: float64

In [10]:
df = pd.DataFrame(emotion_count.tweets)

In [11]:
df.head(7)

          tweets
emotions
anger      72.73
fear        2.60
happy      12.99
love        3.90
sadness     5.19
surprise    2.60

In [12]:
df.to_csv('quater1_2020.csv', sep=',', index=False)

In [13]:
emotion_count = quater2_2020.groupby('emotions').count()
emotion_sum = sum(emotion_count.tweets)
emotion_count.tweets = (emotion_count.tweets * 100 / emotion_sum).round(2)
emotion_count.tweets

emotions
anger       55.84
fear         0.97
happy       36.21
love         2.56
sadness      4.28
surprise     0.14
Name: tweets, dtype: float64

In [14]:
df = pd.DataFrame(emotion_count.tweets)

In [16]:
df.head(7)

          tweets
emotions
anger      55.84
fear        0.97
happy      36.21
love        2.56
sadness     4.28
surprise    0.14

In [15]:
df.to_csv('quater2_2020.csv', sep=',', index=False)

In [17]:
emotion_count = quater3_2020.groupby('emotions').count()
emotion_sum = sum(emotion_count.tweets)
emotion_count.tweets = (emotion_count.tweets * 100 / emotion_sum).round(2)
emotion_count.tweets

emotions
anger      65.0
happy      25.0
sadness    10.0
Name: tweets, dtype: float64

In [18]:
df = pd.DataFrame(emotion_count.tweets)

In [19]:
df.head(7)

          tweets
emotions
anger       65.0
happy       25.0
sadness     10.0

In [20]:
df.to_csv('quater3_2020.csv', sep=',', index=False)

In [21]:
emotion_count = quater4_2020.groupby('emotions').count()
emotion_sum = sum(emotion_count.tweets)
emotion_count.tweets = (emotion_count.tweets * 100 / emotion_sum).round(2)
emotion_count.tweets

emotions
anger    84.62
happy     7.69
love      7.69
Name: tweets, dtype: float64

In [22]:
df = pd.DataFrame(emotion_count.tweets)

In [23]:
df.head(7)

          tweets
emotions
anger      84.62
happy       7.69
love        7.69

In [24]:
df.to_csv('quater4_2020.csv', sep=',', index=False)

In [25]:
emotion_count = quater1_2021.groupby('emotions').count()
emotion_sum = sum(emotion_count.tweets)
emotion_count.tweets = (emotion_count.tweets * 100 / emotion_sum).round(2)
emotion_count.tweets

emotions
anger      78.26
fear        4.35
happy       4.35
sadness    13.04
Name: tweets, dtype: float64

In [26]:
df = pd.DataFrame(emotion_count.tweets)

In [27]:
df.head(7)

          tweets
emotions
anger      78.26
fear        4.35
happy       4.35
sadness    13.04

In [28]:
df.to_csv('quater1_2021.csv', sep=',', index=False)

In [31]:
emotion_count = quater2_2021.groupby('emotions').count()
emotion_sum = sum(emotion_count.tweets)
emotion_count.tweets = (emotion_count.tweets * 100 / emotion_sum).round(2)
emotion_count.tweets

emotions
anger       55.84
fear         0.97
happy       36.21
love         2.56
sadness      4.28
surprise     0.14
Name: tweets, dtype: float64

In [32]:
df = pd.DataFrame(emotion_count.tweets)

In [33]:
df.head(7)

          tweets
emotions
anger      55.84
fear        0.97
happy      36.21
love        2.56
sadness     4.28
surprise    0.14

In [34]:
df.to_csv('quater2_2021.csv', sep=',', index=False)